# my_database and wordpress two container will create and both connect to the bridge network wpnetwork
# and volume created to keep data

version: '3.8'

services:
  my_database:
    image: mysql:5.7
    restart: always
    volumes:
      - mydata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mywordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpnet
    
  wordpress:
    image: wordpress:latest
    depends_on:          # wordpress running on the database, if database does not work no need to create wordpress so create this after my_database
      - my_database
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: my_database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    networks:
      - wpnet

volumes:       # First volumes and network will created before services, always start from the end
  mydata:

networks:
  wpnet:
    driver: bridge   



